#!/bin/bash

if [ -n "$AWS_IAM_ROLE" ]; then
  creds=$(curl -sSf http://169.254.169.254/latest/meta-data/iam/security-credentials/${AWS_IAM_ROLE})
  if [ -z "$creds" ]; then
    echo "FATAL: Couldn't obtain credentials for role ${AWS_IAM_ROLE} from EC2 metadata." >&2
    exit 1
  fi
  AWS_ACCESS_KEY_ID=$(echo $creds | jq -r .AccessKeyId)
  AWS_SECRET_ACCESS_KEY=$(echo $creds | jq -r .SecretAccessKey)
  AWS_SESSION_TOKEN=$(echo $creds | jq -r .Token)
  AWS_DEFAULT_REGION=$(curl -sSf http://169.254.169.254/latest/meta-data/placement/availability-zone | sed -e 's/[a-z]$//')
fi

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo "FATAL: AWS_ACCESS_KEY_ID not set" >&2
  exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "FATAL: AWS_SECRET_ACCESS_KEY not set" >&2
  exit 1
fi

if [ -z "$AWS_DEFAULT_REGION" ]; then
  echo "FATAL: AWS_DEFAULT_REGION not set" >&2
  exit 1
fi

exec /usr/bin/start-aws-kinesis-agent "$@"
